# Build stage
FROM golang:alpine AS builder

WORKDIR /app
COPY . .
RUN go mod tidy
RUN go build -o certslurpd ./cmd/certslurpd


FROM alpine:latest

RUN adduser -D -g '' certslurp
WORKDIR /home/certslurp
COPY --from=builder /app/certslurpd /usr/local/bin/certslurpd

USER certslurp
ENTRYPOINT ["/usr/local/bin/certslurpd"]